packages:
  - packages/*
  - tools/*
  - tests

catalog:
  '@babel/core': ^7.28.5
  browserslist: ^4.28.1
  chalk: ^5.6.2
  cheetor: ^0.13.0
  core-js: ^3.47.0
  core-js-pure: ^3.47.0
  deepmerge-ts: ^7.1.5
  ext-to-regexp: ^0.1.0
  flat: ^6.0.1
  fs-extra: ^11.3.2
  ini: ^6.0.0
  settingz: ^0.2.0
  slash-to-regexp: ^0.1.0
  sort-keys: ^6.0.0
  webpack: ^5.104.0
  yaml: ^2.8.2

catalogs:
  react:
    '@pmmmwh/react-refresh-webpack-plugin': ^0.6.2
    '@types/react': ^18.3.27
    '@types/react-dom': ^18.3.7
    react: ^18.3.1
    react-dom: ^18.3.1
    react-refresh: ^0.18.0

configDependencies:
  pnpm-plugin-nice-move: 0.1.0+sha512-M70sSpJmx0htcWXAYdd+VtlFthhQEHWsfLIINitKLVEWs4NyCOdiyd+zGkcqJE8PwqVPd6hpiNX9edIuvB9wjw==

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - less

minimumReleaseAgeExclude:
  - '@into-mini/*'
  - '@best-shot/*'
  - '@nice-move/*'
  - '@vue/*'
  - vue

patchedDependencies:
  '@vue-mini/core': patches/@vue-mini__core.patch
  ava: patches/ava.patch

shamefullyHoist: true

updateConfig:
  ignoreDependencies:
    - express
    - react
    - react-dom
    - react-refresh

overrides:
  '@into-mini/sfc-template-traverse': 0.1.2
  '@into-mini/sfc-transformer': 0.6.5
  '@into-mini/vue-mini-patch': 0.4.8
  eslint: ^9.39.2
