packages:
  - packages/*
  - tools/*
  - tests

catalog:
  browserslist: ^4.27.0
  chalk: ^5.6.2
  cheetor: ^0.13.0
  core-js: ^3.46.0
  core-js-pure: ^3.46.0
  deepmerge-ts: ^7.1.5
  ext-to-regexp: ^0.1.0
  flat: ^6.0.1
  fs-extra: ^11.3.2
  ini: ^6.0.0
  settingz: ^0.2.0
  slash-to-regexp: ^0.1.0
  sort-keys: ^6.0.0
  webpack: ^5.102.1
  yaml: ^2.8.1

catalogs:
  react:
    react: ^18.3.1
    react-dom: ^18.3.1
    react-refresh: ^0.17.0
    '@pmmmwh/react-refresh-webpack-plugin': ^0.6.1
    '@types/react': ^18.3.26
    '@types/react-dom': ^18.3.7

patchedDependencies:
  '@vue-mini/core': patches/@vue-mini__core.patch
  ava: patches/ava.patch

shamefullyHoist: true

updateConfig:
  ignoreDependencies:
    - express
    - react
    - react-dom
    - react-refresh

minimumReleaseAge: 1440
