packages:
  - packages/*
  - tools/*

catalog:
  browserslist: ^4.24.0
  chalk: ^5.3.0
  cheetor: ^0.13.0
  core-js: ^3.38.1
  core-js-pure: ^3.38.1
  deepmerge-ts: ^7.1.3
  ext-to-regexp: ^0.1.0
  flat: ^6.0.1
  fs-extra: ^11.2.0
  ini: ^5.0.0
  react: ~18.2.0
  react-dom: ~18.2.0
  settingz: ^0.2.0
  slash-to-regexp: ^0.0.4
  sort-keys: ^5.1.0
  webpack: ^5.95.0
  yaml: ^2.6.0
