packages:
  - packages/*
  - tools/*

catalog:
  browserslist: ^4.24.4
  chalk: ^5.4.1
  cheetor: ^0.13.0
  core-js: ^3.41.0
  core-js-pure: ^3.41.0
  deepmerge-ts: ^7.1.5
  ext-to-regexp: ^0.1.0
  flat: ^6.0.1
  fs-extra: ^11.3.0
  ini: ^5.0.0
  react: '>=18.3.1'
  react-dom: '>=18.3.1'
  settingz: ^0.2.0
  slash-to-regexp: ^0.1.0
  sort-keys: ^5.1.0
  webpack: ^5.99.6
  yaml: ^2.7.1
